### ISSUE TITLE
ModuleNotFoundError: No module named 'win32com'

### ISSUE THREAD

**Issue by ShadwMan** [bperian/vintel#21]
When attempting to run in Linux I get the error:
ModuleNotFoundError: No module named 'win32com'

Traceback (most recent call last):
  File "vintel.py", line 30, in <module>
    from vi.ui import viui, systemtray
  File "vintel/src/vi/ui/viui.py", line 42, in <module>
    from vi.soundmanager import SoundManager
  File "vintel/src/vi/soundmanager.py", line 29, in <module>
    from win32com.server.util import wrap
ModuleNotFoundError: No module named 'win32com'

**Comment by bperian** [comment]
Could not reproduce. Will reopen if case arises

**Comment by radub7** [comment]
I have the exact same error.
It's caused by a missing python3 module : pywin32, available for Windows only (I can't pip install it)
```
$ python3 -m pip install pywin32
Collecting pywin32
  ERROR: Could not find a version that satisfies the requirement pywin32 (from versions: none)
ERROR: No matching distribution found for pywin32
```
So I guess it's on our side

**Comment by bperian** [comment]
will get back at it now the blackout period is done

**Comment by wa3x** [comment]
Under Ubuntu 18.04 (all other libs installed)

Traceback (most recent call last):
  File "/home/wax/Vintel/src/vintel.py", line 30, in <module>
    from vi.ui import viui, systemtray
  File "/home/wax/Vintel/src/vi/ui/viui.py", line 42, in <module>
    from vi.soundmanager import SoundManager
  File "/home/wax/Vintel/src/vi/soundmanager.py", line 29, in <module>
    from win32com.server.util import wrap
ModuleNotFoundError: No module named 'win32com'
